name: Update Dengue CSV

on:
  schedule:
    - cron: "30 6 * * *"   # run at 12.30 pm
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("httr","stringr","jsonlite","dplyr","readr"),repos="https://cloud.r-project.org")'

      - name: Run dghs_dengue_dashboard_fetching and update CSV
        run: |
          Rscript dghs_dengue_dashboard_fetching.R

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dengue-dashboard/Dengue daily hospital case data DNCC - daily_dengue_dghs.csv
          git commit -m "Update dengue dghs data $(date)" || echo "No changes"
          git push
